apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow # Or your preferred name
  namespace: argocd       # Argo CD's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jainds/madrigal.git 
    path: k8s/argocd_apps/my-kubeflow 
    targetRevision: e49916d7e17b9cf37bca07b57a2b471e5643ef1f 

    kustomize: {}

  destination:
    server: https://kubernetes.default.svc 
    
    namespace: kubeflow

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # --- Essential for initial sync and fixing inconsistencies ---
      # - Replace=true
      - ApplyOutOfSyncOnly=true

    automated:
      prune: true
      selfHeal: true
